version: "3"

services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "19001:19001"
      - "19006:19006"
    tty: true
    environment:
      - NODE_ENV=development
      - RCT_METRO_PORT=19001
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=<your ip address>
    volumes:
      - ./:/app:delegated
    healthcheck:
      disable: true
      test: ["CMD", "curl", "-f", "http://localhost:19006"]
    stdin_open: true

volumes:
  notused: